### PR TITLE
Remove old jobs when assigning schedule

### PR DESCRIPTION
**Pull request by reneklacan**
Hi there,

I've been using sidekiq sheduler with Rails and I found it bit weird that when I remove a job from my yml file it doesn't get removed and you can still see it in web interface as well.

This fixes it. Let me know what you think!

### CODE REVIEW

**Comment by elpic** [comment]
Hi @reneklacan,

I think it is great. Could you please fix the checks?

Thanks

**Comment by reneklacan** [comment]
@elpic I'm glad you like it. All tests pass locally on my machine and they passed on CI as well when I did rebuild without any change https://travis-ci.org/moove-it/sidekiq-scheduler/builds/97295374

**Comment by elpic** [comment]
@reneklacan this test SidekiqScheduler::Schedule#test_0004_set_schedule is failing, also the other check if for the code coverage if fails it means that the code coverage decreased. 

By the way can you rebase with the latest changes on moove-it remote that way the PR get closed automatically when I do the merge (I merge by command line).

Thanks

**Comment by reneklacan** [comment]
@elpic If you take a look on the test which failed it has nothing to do with the code I changed and when I did rebuild I linked before (https://travis-ci.org/moove-it/sidekiq-scheduler/builds/97295374) it passed so it's probably just bit flaky test. (I can add empty commit to this branch to prove it passes, I just removed it after I tried it and I don't have permission to hit rebuild button on the Travis CI, try it).

For coverage check if you take a look on the detail then you find out that coverage decreased for file I haven't touched so it's irrelevant as well.

PR is rebased on the current master.

Thanks

**Comment by elpic** [comment]
It's merged, tomorrow probably I will release a new version with this and a .gemspec update.

**Comment by reneklacan** [comment]
Thanks!

**Pull request merged**
