### PR TITLE
fix: add Sidekiq::Component

### PR DESCRIPTION
**Pull request by mihaic195**
Based on https://github.com/moove-it/sidekiq-scheduler/pull/382#issuecomment-1149775977 
Thanks for pointing that out. Indeed, it seems it was just replaced by a different name. @ltello @marcelolx

### CODE REVIEW

**Comment by ltello** [comment]
Cool

**Comment by marcelolx** [comment]
@ltello @mihaic195 Please see my comments on https://github.com/moove-it/sidekiq-scheduler/pull/382

**Comment by mihaic195** [comment]
> @ltello @mihaic195 Please see my comments on #382

Good point, indeed. I agree.
You can close this PR if you think it's not relevant.

**Comment by marcelolx** [comment]
I've also added one more comment https://github.com/moove-it/sidekiq-scheduler/pull/382#issuecomment-1149803452, basically, we aren't even using currently `sidekiq/util`, so one more reason to not depend on `Sidekiq::Component`.

Anyway, thank you both for your help! I really appreciate it ❤️

**Pull request closed without merging**
