### PR TITLE
Fix deprecation warning for exists; Upgrade redis and mock_redis dependencies

### LINKED ISSUE #305: Deprecation warning from redis-rb
I am now getting deprecation warnings in my sidekiq.log

`Redis#exists(key)` will return an Integer in redis-rb 4.3. 
`exists?` returns a boolean, you should use it instead. To opt-in to the new behavior now you can set Redis.exists_returns_integer =  true. To disable this message and keep the current (boolean) behaviour of 'exists' you can set `Redis.exists_returns_integer = false`, but this option will be removed in 5.0. 

```
(/var/www/bestappever/shared/bundle/ruby/2.6.0/gems/sidekiq-6.0.7/lib/sidekiq/launcher.rb:160:in `block (2 levels) in ❤')
```

### PR DESCRIPTION
**Pull request by rmm5t**
## What does it do?

- Upgrade redis dependency
- Upgrade mock_redis
- Fix pending specs
- Use strings as keys instead of symbols

## What else do you need to know?

- The redis gem converts all keys from symbols to strings, but mock_redis does not. This PR helps remedy that discrepancy.

## Related Issues

- Fixes #305
- Closes #306

### CODE REVIEW

**Review by akhil-vineti — APPROVED** [review]
LGTM 🎉

**Comment by akhil-vineti** [comment]
@snmgian Can we please get this merged?

**Comment by jdongelmans** [comment]
Any update? It's been quite a while since these warnings started popping up and the list of PR's regarding this keeps growing 😉

**Comment by etiennemartin** [comment]
We are also seeing these warnings in our build. 🙏 Can this be merged?

**Comment by marcelolx** [comment]
Thanks for this @rmm5t! The deprecation warning already has been fixed on this PR https://github.com/moove-it/sidekiq-scheduler/pull/335.

I think we can consider merge the part related to using the keys as strings, but we don't want to drop support for ruby 2.2/2.3 and redis < 4.2, that would require a major release which is not the focus at the moment.

Feel free to send a PR with the changes related to the symbol keys, I'll be happy to review it!

**Pull request closed without merging**
