### PR TITLE
Fix dependency for ruby 2.7.0

### PR DESCRIPTION
**Pull request by biow0lf**

### CODE REVIEW

**Comment by olegantonyan** [comment]
@biow0lf any ideas why tests failed?

**Comment by PhilCoggins** [comment]
@biow0lf @olegantonyan Failures could be due to updates in https://github.com/sds/mock_redis lib. Locking version to 0.19.0 gets green specs for me on both 2.7.0 and 2.6.5.

```ruby
s.add_development_dependency 'mock_redis',              '= 0.19.0'
```

**Comment by biow0lf** [comment]
> @biow0lf any ideas why tests failed?

If this is blocking, I can fix this.

**Comment by snmgian** [comment]
The changes in this PR are already merged. Thanks.

**Pull request closed without merging**
