### PR TITLE
Config hashie object with indifferent access

### PR DESCRIPTION
**Pull request by hunzinker**
Thanks for the great gem!

I noticed a bug where `ActiveJob` scheduled jobs do not recognize jobs scheduled with a `queue` key value.

ENV:
```
    rails (4.2.7.1)
    sidekiq (4.2.10)
    sidekiq-pro (3.4.5)
    sidekiq-scheduler (2.1.2)
```

Example Scheduler:
```
 job_name:
    cron: "30 0 * * * America/Los_Angeles"
    class: WorkerClass
    args: ["args", "for", "worker"]
    queue: "host-specific-queue"
    description: "process stuff"
```
 
The scheduled job above, is parsed as a hash with stringified keys. When the hash is passed to `WorkerClass.enqueue(config)` the stringified keys are ignored and the job is enqueued on the `default` queue unless `queue_as` is set.

Solution:
The gem is already including `Hashie` so I propose converting the config hash to a hashie hash with indifferent access before enqueuing.

I have not tested this change in Rails 5 so it's unclear if the hash with indifferent access is needed.

Current Workaround:
To avoid this issue, I added the below:

```ruby
class ApplicationJob < ActiveJob::Base
  def enqueue(options = {})
    super(options.symbolize_keys)
  end
end
```

This PR is intended as a example solution to open dialogue.

Thanks!

### CODE REVIEW

**Comment by snmgian** [comment]
Hi @hunzinker, thanks for finding and tracking down this.

ActiveJob instances receive these options through method `#enqueue`:
 - http://api.rubyonrails.org/classes/ActiveJob/Enqueuing.html#method-i-enqueue
 - http://api.rubyonrails.org/v4.2.3/classes/ActiveJob/Enqueuing.html#method-i-enqueue

So, instead of having a hash with indifferent access, why not simply build that options hash?

Doing that will also prevent us to pass to `#enqueue` the other options like `class` and `args`, though it seems that there's no problem passing those extra options, I think its better to stick to `#enqueue` documentation.

I pushed another PR with that proposal: PR #177 

I've tested that approach in Rails v4.2.3 and Rails v5.0.2

Thoughts?

**Comment by hunzinker** [comment]
@snmgian thanks for the feedback!

After reviewing your PR I noticed one concern with https://github.com/moove-it/sidekiq-scheduler/pull/177/files#diff-d5f01781450b17c68db7c73404edd78bR233

Why limit to only passing `enqueue`? It's possible a user would want to provide `priority` via the `sidekiq_scheduler.yml` as well? When Rails 6 is released some awesome new option `key => value`.

My proposal, converting the options hash to a hash with indifferent access, covers having to make specific changes for sidekiq and active_job should they arise.

It boils down to how you want to handle the problem in the end. That's where I'll defer to you since you're the expert. :)

**Comment by snmgian** [comment]
Allowing users to pass in options to `#enqueue` is a nice feature. But those options should be specified at a different level in the configuration hierarchy to prevent any collision with former schedule's options.

What if in Rails 6 an option named `include_metadata` is added? What if we want to  add a `wait` config option with different semantics than `#enqueue`'s wait option? What if in a future version of ActiveJob it starts to emit warnings when unkown options are passed in?

Those issues will be prevented by grouping options in a separate key. This is an example of such configuration:

``` yaml
 job_name:
    cron: "30 0 * * * America/Los_Angeles"
    class: WorkerClass
    args: ["args", "for", "worker"]
    queue: "host-specific-queue"
    include_metadata: true
    wait: true # Wait any previous job to finish
    description: "process stuff"
    actvejob: # ActiveJob specific options
      wait: 5.minutes
      include_metadata: { host: 'localhost' }
```

**Comment by snmgian** [comment]
PR #177 merged

**Comment by snmgian** [comment]
v2.1.3 released

**Pull request closed without merging**
