### PR TITLE
Upgrade to sidekiq 4.x

### PR DESCRIPTION
**Pull request by hesham**
Also removed celluloid dependency since it's not longer required in sidekiq 4.0.

All tests pass. Please let me know if I missed anything.

### CODE REVIEW

**Comment by reneklacan** [comment]
:+1:

**Comment by elpic** [comment]
@hesham 

Would be possible to use the >= 3 for the sidekiq version?

Thanks

**Comment by hesham** [comment]
@stephankaag @elpic Good point. Honestly, I wasn't sure if removing Celluloid dependency will render the gem incompatible with sidekiq 3.x. That said, all tests seem to pass with >= 3. So I'll make that change.

**Comment by elpic** [comment]
I think i was an old code, the celluloid dependency is not necessary on neither of those versions.

**Comment by hesham** [comment]
@elpic Awesome. I made the change.

**Comment by elpic** [comment]
@hesham 

Could you squash the commits? 

Thanks.

**Comment by hesham** [comment]
@elpic yep

**Comment by elpic** [comment]
closes #65

**Comment by emerleite** [comment]
Any plan to a 1.2.5 with this update?

**Comment by elpic** [comment]
I want to update this with the ability to dynamically update the schedule and release the 2.0 version. Probably later this week.

**Comment by stephankaag** [comment]
:+1:

**Comment by elpic** [comment]
@emerleite sorry, I forgot to mention that the version 2.0.0 was released. That version is compatible with the new version of sidekiq and include the dynamic update of schedules.

**Pull request closed without merging**
