### PR TITLE
Remove Sidekiq::Util

### LINKED ISSUE #381: Sidekiq 6.5.0 upgrade is breaking this gem
Please see this comment - https://github.com/mperham/sidekiq/issues/5372#issuecomment-1148916402

Error
```
/Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require': cannot load such file -- sidekiq/util (LoadError)
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:15:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler/scheduler.rb:2:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq/scheduler.rb:1:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler.rb:4:in `require_relative'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/sidekiq-scheduler-4.0.0/lib/sidekiq-scheduler.rb:4:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:60:in `block (2 levels) in require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `each'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:55:in `block in require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `each'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler/runtime.rb:44:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bundler-2.3.10/lib/bundler.rb:176:in `require'
	from /Users/kapil/projects/tradespace/config/application.rb:7:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:137:in `block in perform'
	from <internal:kernel>:90:in `tap'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands/server/server_command.rb:134:in `perform'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/command.rb:27:in `run'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor/invocation.rb:127:in `invoke_command'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/thor-1.2.1/lib/thor.rb:392:in `dispatch'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command/base.rb:87:in `perform'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/command.rb:48:in `invoke'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/railties-7.0.3/lib/rails/commands.rb:18:in `<main>'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from /Users/kapil/.rbenv/versions/3.1.2/lib/ruby/gems/3.1.0/gems/bootsnap-1.12.0/lib/bootsnap/load_path_cache/core_ext/kernel_require.rb:30:in `require'
	from bin/rails:4:in `<main>'
```

### PR DESCRIPTION
**Pull request by mihaic195**
Fixes #381

### CODE REVIEW

**Comment by marcelolx** [comment]
I tested the changes locally and it seems that this does the trick! Thank you!

**Comment by ltello** [comment]
sidekiq/util has been replace with sidekiq/component in sidekiq 6.5.0.
Why not make the replacement in this gem instead of removing it? Is sidekiq/util not needed by this gem at all?

**Comment by marcelolx** [comment]
@ltello The problem with that is that Sidekiq::Component does only exist in Sidekiq 6.5 which would force us to bump a major release of sidekiq-scheduler and this major release would require Sidekiq >= 6.5

**Comment by marcelolx** [comment]
Also, I believe that `sidekiq/util` is not needed at all by this gem, the only method we were using was the `logger` which we can access without requiring this internal API (maybe in older versions of sidekiq it was required, but doesn't seem to be anymore)

**Comment by marcelolx** [comment]
Another important thing to note is that we have been accessing the logger through Sidekiq.logger, including `sidekiq/util` would have allowed us to access it directly  `logger` which we don't do, so I don't see reasons for requiring that file.

Looking at the history, it seems that since https://github.com/moove-it/sidekiq-scheduler/pull/238 we didn't depend anymore on any method of `sidekiq/util`, before we did access `logger` directly https://github.com/moove-it/sidekiq-scheduler/pull/238/files#diff-0ddd2bcc9bd29aac261acdd76530920c85887c269cc29e3f054e465b4ac8699eL76 but with that refactor we don't do anymore

**Pull request merged**
